target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
  #pod 'shared', :path => '../shared'
  pod 'CryptoSwift'
  pod 'MatrixSDK/SwiftSupport'
  pod 'SQLite.swift'
  pod 'web3swift', :git => 'https://github.com/jimmyneutront/web3swift.git', :branch => 'develop'
  target :iosAppTests
end