target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
  #pod 'shared', :path => '../shared'
  pod 'SQLite.swift'
  pod 'MatrixSDK'
  pod 'web3swift', :git => 'https://github.com/jimmyneutront/web3swift.git'
end